// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhmpVnToLIkeEiDHMZz-bPvINKITdlQK0',
    appId: '1:274541242092:web:fedeedb75a4fc5f5c9a7c9',
    messagingSenderId: '274541242092',
    projectId: 'groceryapp-c79b7',
    authDomain: 'groceryapp-c79b7.firebaseapp.com',
    storageBucket: 'groceryapp-c79b7.firebasestorage.app',
    measurementId: 'G-51QLD4TRH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRcGmE8tYuMigvXQZmTZeqCroluWynzUU',
    appId: '1:934857001328:android:4b98155b51ecb4c1eba7b5',
    messagingSenderId: '934857001328',
    projectId: 'groccery-28ebb',
    storageBucket: 'groccery-28ebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdtoAdL8ovkx5BuSHuU79D5HOnZuuq4ts',
    appId: '1:274541242092:ios:9964f0799c3560d5c9a7c9',
    messagingSenderId: '274541242092',
    projectId: 'groceryapp-c79b7',
    storageBucket: 'groceryapp-c79b7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdtoAdL8ovkx5BuSHuU79D5HOnZuuq4ts',
    appId: '1:274541242092:ios:9964f0799c3560d5c9a7c9',
    messagingSenderId: '274541242092',
    projectId: 'groceryapp-c79b7',
    storageBucket: 'groceryapp-c79b7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhmpVnToLIkeEiDHMZz-bPvINKITdlQK0',
    appId: '1:274541242092:web:350f3281c5ed4a75c9a7c9',
    messagingSenderId: '274541242092',
    projectId: 'groceryapp-c79b7',
    authDomain: 'groceryapp-c79b7.firebaseapp.com',
    storageBucket: 'groceryapp-c79b7.firebasestorage.app',
    measurementId: 'G-QDBLDLZ0R3',
  );
}